const s=loadSettings();
const text=qs('#text'),speed=qs('#speed'),size=qs('#size'),margin=qs('#margin'),color=qs('#color');
text.innerHTML=s.html||s.text||'';speed.value=s.speed;size.value=s.fontSize;margin.value=s.margin;color.value=s.color;
let running=false,offset=0,last=0,mirror=!!s.mirror,invert=!!s.invert,peer,hostCode,connections=new Set(),countTimer=null;
function html(){return text.innerHTML.trim()} function plain(){return text.innerText.trim()}
function state(){return {html:html(),speed:+speed.value,fontSize:+size.value,margin:+margin.value,color:color.value,mirror,invert,running,offset}}
function render(){const p=qs('#prompt');p.innerHTML=html()||'<span style="opacity:.45">Ajoutez un texte…</span>';p.style.fontSize=size.value+'vw';p.style.marginLeft=margin.value+'%';p.style.marginRight=margin.value+'%';p.style.color=color.value;p.style.filter=invert?'invert(1)':'none';p.style.transform='translateY('+(-offset)+'px)'+(mirror?' scaleX(-1)':'')}
function ui(){qs('#speedV').textContent=(+speed.value).toFixed(1)+'×';qs('#sizeV').textContent=size.value+'vw';qs('#marginV').textContent=margin.value+'%'}
function broadcast(m){connections.forEach(c=>{if(c.open)c.send(m)})}
function save(){saveSettings({html:html(),text:html(),speed:+speed.value,fontSize:+size.value,margin:+margin.value,color:color.value,mirror,invert});ui();render();broadcast({type:'state',state:state()})}
text.addEventListener('input',save);[speed,size,margin,color].forEach(x=>x.addEventListener('input',save));
qs('.toolbar').querySelectorAll('button').forEach(b=>b.addEventListener('mousedown',e=>e.preventDefault()));qs('.toolbar').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);text.focus();save()}));
function loop(t){if(!running)return;const d=Math.min(80,t-(last||t));last=t;offset+=d*.035*+speed.value;render();requestAnimationFrame(loop)}
function play(v){running=v;if(v){last=0;requestAnimationFrame(loop)}else last=0;qs('#play').textContent=v?'Ⅱ':'▶';broadcast({type:'state',state:state()})}
function action(a){if(a==='play')play(!running);if(a==='back')offset=Math.max(0,offset-180);if(a==='forward')offset+=180;if(a==='slower')speed.value=Math.max(.2,+speed.value-.1);if(a==='faster')speed.value=Math.min(4,+speed.value+.1);if(a==='smaller')size.value=Math.max(2,+size.value-.5);if(a==='larger')size.value=Math.min(12,+size.value+.5);if(a==='restart'){offset=0;play(false)}if(a==='mirror')mirror=!mirror;save()}
['play','back','forward','slower','faster','smaller','larger','restart'].forEach(id=>qs('#'+id)?.addEventListener('click',()=>action(id)));qs('#mirror2').onclick=()=>action('mirror');
async function goFullscreen(){try{if(!document.fullscreenElement)await qs('#stage').requestFullscreen()}catch{toast('Plein écran bloqué : utilisez ⛶')}}
qs('#fullscreen').onclick=goFullscreen;qs('#exit').onclick=()=>{play(false);if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});qs('#stage').hidden=true;qs('#setup').style.display='block'};
qs('#launch').onclick=()=>{if(!plain())return toast('Écrivez d’abord votre texte.');qs('#launchModal').classList.add('open')};qs('#closeLaunch').onclick=()=>qs('#launchModal').classList.remove('open');
function startLaunch(n){qs('#launchModal').classList.remove('open');clearInterval(countTimer);if(!n){openStage();return}qs('#count').hidden=false;let x=n;qs('#countNum').textContent=x;countTimer=setInterval(()=>{x--;if(x<=0){clearInterval(countTimer);countTimer=null;qs('#count').hidden=true;openStage()}else qs('#countNum').textContent=x},1000)}
qs('#launchModal').querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>startLaunch(+b.dataset.count));qs('#count').onclick=()=>{if(countTimer){clearInterval(countTimer);countTimer=null;qs('#count').hidden=true;toast('Lancement annulé')}};
function openStage(){qs('#setup').style.display='none';qs('#stage').hidden=false;offset=0;render();setTimeout(()=>{goFullscreen();play(true)},60)}
function status(){const ok=connections.size>0;qs('#statusDot').classList.toggle('ok',ok);qs('#statusText').textContent=ok?connections.size+' télécommande(s) connectée(s)':'Aucune télécommande';qs('#peers').textContent=qs('#statusText').textContent}
function host(){hostCode=makeCode();peer=new Peer('pt-'+hostCode,{debug:0});peer.on('open',()=>{qs('#code').textContent=hostCode;qs('#qr').innerHTML='';new QRCode(qs('#qr'),{text:new URL('remote.html',location.href).href+'?code='+hostCode,width:200,height:200})});peer.on('connection',c=>{connections.add(c);status();c.on('open',()=>c.send({type:'state',state:state()}));c.on('data',m=>{if(m?.type==='command')action(m.action)});c.on('close',()=>{connections.delete(c);status()});c.on('error',()=>{connections.delete(c);status()})});peer.on('error',e=>{if(e.type==='unavailable-id'){peer.destroy();setTimeout(host,200)}else toast('Impossible de créer la connexion.')});peer.on('disconnected',()=>peer.reconnect())}
qs('#connect').onclick=()=>qs('#modal').classList.add('open');qs('#closeModal').onclick=()=>qs('#modal').classList.remove('open');
let hide;qs('#stage').addEventListener('mousemove',()=>{qs('#stage').classList.add('show-controls');clearTimeout(hide);hide=setTimeout(()=>qs('#stage').classList.remove('show-controls'),2500)});qs('#stage').addEventListener('touchstart',()=>qs('#stage').classList.add('show-controls'),{passive:true});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&countTimer){clearInterval(countTimer);countTimer=null;qs('#count').hidden=true;return}if(qs('#stage').hidden)return;if(e.key===' '){e.preventDefault();action('play')}else if(e.key==='ArrowLeft')action('back');else if(e.key==='ArrowRight')action('forward');else if(e.key.toLowerCase()==='r')action('restart')});
host();ui();render();